apiVersion: v1
kind: Service
metadata:
  name: links-api-service
spec:
  selector:
    app: links_api
  ports:
  - protocol: "TCP"
    port: 8030
    targetPort: 80
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: links-api
spec:
  selector:
    matchLabels:
      app: links_api
  replicas: 4
  template:
    metadata:
      labels:
        app: links_api
    spec:
      containers:
      - name: links-api-base
        image: links_api:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80